[tools]
python = "3.14"
uv = "latest"

[settings]
python.uv_venv_auto = "create|source"

[env]
UV_PYTHON = { value = "{{ tools.python.path }}", tools = true }
UV_CACHE_DIR = "{{config_root}}/.uv-cache"

[tasks.sync]
description = "Sync the project environment"
run = "uv sync"
sources = ["pyproject.toml", "uv.lock"]
outputs = [".venv"]

